import locale

LANGUAGE_CODES = {
    "zh_CN": "Mandarin (Simplified)",
    "ja_JP": "Japanese",
    "fr_FR": "French",
    "es_ES": "Spanish",
    "it_IT": "Italian",
    "de_DE": "German",
    "pt_BR": "Portuguese",
    "ru_RU": "Russian",
    "ko_KR": "Korean",
    "en_US": "English",  # Default lang
    "pl_PL": "Polish",
    "uk_UA": "Ukrainian",
    "hi_IN": "Hindi",
    "ar_SA": "Arabic",
    "id_ID": "Indonesian",
}

TRANSLATIONS = {
    "Mandarin (Simplified)": {
        "title": "文件转换器",
        "select_file": "选择文件",
        "convert": "转换",
        "download": "下载",
        "error": "错误",
        "success": "成功",
        "dropzone_diff": "Dropzone 模式要求输入和输出必须不同",
        "dropzone_active": "Dropzone 模式已启用。按 CTRL+C 停止。正在监视：",
        "no_out_multi_in": "使用多个输入路径时未提供输出路径",
        "no_media_found": "在 [path] 中未找到可转换的媒体文件",
        "skipping": "跳过",
        "no_media_general": "无可转换的媒体文件",
        "job_finished": "作业完成",
        "output_list": "输出格式必须是以下之一：[list]",
        "scheduling": "我计划",
        "scanning": "查看",
        "no_dir_exist": "[dir] 目录不存在",
        "source_rate_incompatible": "源采样率与 [format] 不兼容。尝试使用兼容的速率...",
        "no_audio": "在 [path] 中未找到音频",
        "audio_extract_fail": "无法从仅音频文件 [path] 中提取音频",
        "codec_fallback": "编解码器与 [path] 不兼容：改用兼容格式 [format]...",
        "unsupported_stream": "不支持的流协议：",
        "get_hls": "正在为创建 HLS 流：",
        "get_hls_master": "正在为 HLS 流创建主播放列表：",
        "get_hls_fail": "创建 HLS 失败：",
        "create_dash": "正在为创建 DASH 流：",
        "dash_fail": "创建 DASH 失败：",
        "extract_subtitles": "正在提取字幕：",
        "subtitles_success": "字幕成功提取到：",
        "extract_subtitles_alt": "未找到专用字幕轨道。尝试提取嵌入式文本...",
        "embed_subtitles_success": "嵌入式字幕成功提取到：",
        "embed_subtitles_fail": "嵌入式字幕提取失败：",
        "extract_subtitles_fail": "提取字幕失败：",
        "ffmpeg_not_found": "未找到 FFmpeg。安装 FFmpeg 以提取字幕",
        "set_out_dir": "设置输出目录为：",
        "movie_format_unsupported": "不支持的电影格式：",
        "audio_only_video": "仅音频视频文件",
        "merging_pdfs": "正在将 [count] 个 PDF 合并到 [path]",
        "unsupported_format": "不支持的格式",
        "concat_success": "连接完成",
        "no_audio_movie_match": "未找到音频文件与电影文件匹配",
        "converted": "转换完成",
        "removed": "已删除",
        "description": "将媒体文件转换为不同格式",
        "input_help": "包含待转换媒体文件的目录，未指定时使用工作目录",
        "output_help": "保存转换后文件的目录，未指定时使用工作目录",
        "format_help": "设置输出格式：",
        "merge_help": "按电影文件将同名音频合并为一个视频",
        "concat_help": "将同类型文件（图像/视频/音频）依次拼接",
        "framerate_help": "设置输出帧率（默认与输入相同）",
        "quality_help": "设置输出质量（高、中、低）",
        "delete_help": "转换后删除输入文件",
        "web_help": "忽略其他参数，启动网页服务和前端界面",
        "across_help": "在所有输入目录中统一合并/拼接，而不是分别处理",
        "recursive_help": "递归查找子目录中的输入文件",
        "dropzone_help": "待转换文件的拖放区域，将使用输入目录，需指定输出目录",
        "locale_help": f"设置 CLI 的语言。默认值为系统语言（支持的语言：{', '.join(LANGUAGE_CODES.keys())})",
        "lang_not_supported": f"不支持的语言（支持的语言：{', '.join(LANGUAGE_CODES.keys())})",
    },
    "Japanese": {
        "title": "ファイルコンバーター",
        "select_file": "ファイルを選択",
        "convert": "変換",
        "download": "ダウンロード",
        "error": "エラー",
        "success": "成功",
        "dropzone_diff": "ドロップゾーンモードでは、入力と出力を明確に分ける必要があります",
        "dropzone_active": "ドロップゾーンモード有効。CTRL+C で停止。観察：",
        "no_out_multi_in": "複数の入力パスを使用しているのに出力パスが指定されていません",
        "no_media_found": "[path] に変換可能なメディアファイルが見つかりませんでした",
        "skipping": "スキップ中",
        "no_media_general": "変換可能なメディアファイルがありません",
        "job_finished": "ジョブ完了",
        "output_list": "出力形式は次のいずれかでなければなりません：[list]",
        "scheduling": "予定しています",
        "scanning": "読取中",
        "no_dir_exist": "[dir] ディレクトリは存在しません",
        "source_rate_incompatible": "[format] と互換性のないソースサンプリングレート。代わりに互換性のあるレートを使用しています...",
        "no_audio": "[path] に音声が見つかりません",
        "audio_extract_fail": "音声専用ファイル [path] から音声の抽出に失敗しました",
        "codec_fallback": "[Path] と互換性のないコーデック：代わりに互換性のあるフォーマット [format] を試行中…",
        "unsupported_stream": "サポートされていないストリーミングプロトコル：",
        "get_hls": "次の対象に対して HLS ストリームを作成中：",
        "get_hls_master": "HLS ストリームのマスタープレイリストを作成中：",
        "get_hls_fail": "HLS の作成に失敗しました：",
        "create_dash": "次の対象に対して DASH ストリームを作成中：",
        "dash_fail": "DASH の作成に失敗しました：",
        "extract_subtitles": "字幕を抽出中：",
        "subtitles_success": "字幕が正常に抽出されました：",
        "extract_subtitles_alt": "専用の字幕トラックが見つかりませんでした。埋め込まれたテキストを抽出しようとしています...",
        "embed_subtitles_success": "埋め込まれた字幕が正常に抽出されました：",
        "embed_subtitles_fail": "埋め込まれた字幕の抽出に失敗しました：",
        "extract_subtitles_fail": "字幕の抽出に失敗しました：",
        "ffmpeg_not_found": "FFmpeg が見つかりません。字幕を抽出するには FFmpeg をインストールしてください",
        "set_out_dir": "出力ディレクトリを設定しています：",
        "movie_format_unsupported": "サポートされていない映画形式：",
        "audio_only_video": "オーディオ専用ビデオファイル",
        "merging_pdfs": "[count] 個の PDF を [path] にマージしています",
        "unsupported_format": "サポートされていない形式",
        "concat_success": "連結完了",
        "no_audio_movie_match": "映画ファイルと一致する音声ファイルが見つかりません",
        "converted": "変換完了",
        "removed": "削除されました",
        "description": "メディアファイルを異なる形式に変換する",
        "input_help": "変換対象のメディアファイルがあるディレクトリ。未指定時は作業ディレクトリを使用",
        "output_help": "変換後のファイルを保存するディレクトリ。未指定時は作業ディレクトリを使用",
        "format_help": "出力形式を設定：",
        "merge_help": "同名の音声ファイルを動画と結合",
        "concat_help": "同じ種類のファイル（画像／動画／音声）を順番に連結",
        "framerate_help": "出力のフレームレートを設定（デフォルトは入力と同じ）",
        "quality_help": "出力品質を設定（高・中・低）",
        "delete_help": "変換後に入力ファイルを削除",
        "web_help": "他の引数を無視してWebサーバーとフロントエンドを起動",
        "across_help": "各入力ディレクトリごとではなく、全体で結合または連結を実行",
        "recursive_help": "サブディレクトリ内も再帰的に検索して入力ファイルを探す",
        "dropzone_help": "変換対象ファイルのドロップゾーン。入力ディレクトリが使用され、出力ディレクトリは別に指定する必要あり",
        "locale_help": f"CLI の言語を設定します。デフォルトはシステムのロケールです（サポートされている言語：{', '.join(LANGUAGE_CODES.keys())})",
        "lang_not_supported": f"サポートされていない言語（サポートされている言語：{', '.join(LANGUAGE_CODES.keys())})",
    },
    "French": {
        "title": "Convertisseur de fichiers",
        "select_file": "Sélectionner un fichier",
        "convert": "Convertir",
        "download": "Télécharger",
        "error": "Erreur",
        "success": "Succès",
        "dropzone_diff": "Le mode dropzone exige que l’entrée et la sortie soient distinctes",
        "dropzone_active": "Mode dropzone actif. Appuyez sur CTRL+C pour arrêter. Observe:",
        "no_out_multi_in": "Aucun chemin de sortie fourni avec plusieurs chemins d'entrée",
        "no_media_found": "Aucun fichier média convertible trouvé dans [path]",
        "skipping": "Ignoré",
        "no_media_general": "Aucun fichier multimédia convertible",
        "job_finished": "Travail terminé",
        "output_list": "Le format de sortie doit être l'un des suivants : [list]",
        "scheduling": "Programmer",
        "scanning": "En train de scanner",
        "no_dir_exist": "Le répertoire [dir] n'existe pas",
        "source_rate_incompatible": "La fréquence d'échantillonnage source n'est pas compatible avec [format]. Utilisation d'une fréquence compatible...",
        "no_audio": "Aucun audio trouvé dans [path]",
        "audio_extract_fail": "Échec de l'extraction de l'audio du fichier audio seul [path]",
        "codec_fallback": "Codec incompatible avec [path] : tentative avec le format compatible [format]...",
        "unsupported_stream": "Protocole de streaming non pris en charge :",
        "get_hls": "Création d'un flux HLS pour :",
        "get_hls_master": "Création de la playlist principale pour le flux HLS :",
        "get_hls_fail": "Échec de la création de HLS :",
        "create_dash": "Création d'un flux DASH pour :",
        "dash_fail": "Échec de la création de DASH :",
        "extract_subtitles": "Extraction des sous-titres de :",
        "subtitles_success": "Sous-titres extraits avec succès vers :",
        "extract_subtitles_alt": "Aucune piste de sous-titres dédiée trouvée. Essai d'extraction du texte intégré...",
        "embed_subtitles_success": "Sous-titres intégrés extraits avec succès vers :",
        "embed_subtitles_fail": "Échec de l'extraction des sous-titres intégrés :",
        "extract_subtitles_fail": "Échec de l'extraction des sous-titres :",
        "ffmpeg_not_found": "FFmpeg introuvable. Installez FFmpeg pour extraire les sous-titres",
        "set_out_dir": "Définir le répertoire de sortie sur :",
        "movie_format_unsupported": "Format de film non pris en charge :",
        "audio_only_video": "Fichier vidéo audio uniquement",
        "merging_pdfs": "Fusion de [count] PDF dans [path]",
        "unsupported_format": "Format non pris en charge",
        "concat_success": "Concaténation terminée",
        "no_audio_movie_match": "Aucun fichier audio trouvé pour fusionner avec les fichiers vidéo",
        "converted": "Converti",
        "removed": "Supprimé",
        "description": "Convertir des fichiers multimédias en différents formats",
        "input_help": "Dossier contenant les fichiers à convertir. Utilise le dossier de travail si non précisé",
        "output_help": "Dossier de sauvegarde des fichiers convertis. Utilise le dossier de travail si non précisé",
        "format_help": "Définir le format de sortie :",
        "merge_help": "Fusionner avec le fichier audio de même nom par vidéo",
        "concat_help": "Concaténer les fichiers du même type (image/vidéo/audio) à la suite",
        "framerate_help": "Définir le taux de rafraîchissement de sortie (par défaut : identique à l’entrée)",
        "quality_help": "Définir la qualité de sortie (haute, moyenne, basse)",
        "delete_help": "Supprimer les fichiers d’entrée après conversion",
        "web_help": "Ignore tous les autres paramètres, lance le serveur web et l’interface",
        "across_help": "Fusion ou concaténation à travers tous les dossiers d’entrée, pas un par un",
        "recursive_help": "Rechercher récursivement dans les sous-dossiers",
        "dropzone_help": "Zone de dépôt pour les fichiers à convertir ; le dossier d’entrée sera utilisé, un dossier de sortie distinct est requis",
        "locale_help": f"Définir la langue pour la CLI. La valeur par défaut est la langue du système (pris en charge : {', '.join(LANGUAGE_CODES.keys())})",
        "lang_not_supported": f"Langue non prise en charge (prises en charge : {', '.join(LANGUAGE_CODES.keys())})",
    },
    "Spanish": {
        "title": "Convertidor de archivos",
        "select_file": "Seleccionar archivo",
        "convert": "Convertir",
        "download": "Descargar",
        "error": "Error",
        "success": "Éxito",
        "dropzone_diff": "El modo portapapeles requiere que origen y destino sean distintos",
        "dropzone_active": "Modo dropzone activo. Pulsa CTRL+C para detener. Observe:",
        "no_out_multi_in": "No se proporcionó ruta de salida al usar múltiples rutas de entrada",
        "no_media_found": "No se encontraron archivos multimedia convertibles en [path]",
        "skipping": "Omitiendo",
        "no_media_general": "No hay archivos multimedia convertibles",
        "job_finished": "Trabajo terminado",
        "output_list": "El formato de salida debe ser uno de [list]",
        "scheduling": "Programo",
        "scanning": "Escaneando",
        "no_dir_exist": "El directorio [dir] no existe",
        "source_rate_incompatible": "La frecuencia de muestreo de origen no es compatible con [format]. Intentando una frecuencia compatible en su lugar...",
        "no_audio": "No se encontró audio en [path]",
        "audio_extract_fail": "Error al extraer el audio del archivo solo audio [path]",
        "codec_fallback": "Codec incompatible con [path]: probando el formato compatible [format] en su lugar...",
        "unsupported_stream": "Protocolo de transmisión no compatible:",
        "get_hls": "Creando flujo HLS para:",
        "get_hls_master": "Creando lista de reproducción maestra para flujo HLS:",
        "get_hls_fail": "Error al crear HLS:",
        "create_dash": "Creando flujo DASH para:",
        "dash_fail": "Error al crear DASH:",
        "extract_subtitles": "Extrayendo subtítulos de:",
        "subtitles_success": "Subtítulos extraídos con éxito a:",
        "extract_subtitles_alt": "No se encontró una pista de subtítulos dedicada. Intentando extraer texto incrustado...",
        "embed_subtitles_success": "Subtítulos incrustados extraídos con éxito a:",
        "embed_subtitles_fail": "Error al extraer subtítulos incrustados:",
        "extract_subtitles_fail": "Error al extraer subtítulos:",
        "ffmpeg_not_found": "FFmpeg no encontrado. Instale FFmpeg para extraer subtítulos",
        "set_out_dir": "Estableciendo el directorio de salida en:",
        "movie_format_unsupported": "Formato de película no compatible:",
        "audio_only_video": "Archivo de video solo de audio",
        "merging_pdfs": "Fusionando [count] PDFs en [path]",
        "unsupported_format": "Formato no compatible",
        "concat_success": "Concatenación completada",
        "no_audio_movie_match": "No se encontraron archivos de audio para fusionar con archivos de película",
        "converted": "Convertido",
        "removed": "Eliminado",
        "description": "Convertir archivos multimedia a diferentes formatos",
        "input_help": "Directorio con archivos a convertir; se usa el directorio de trabajo si no se indica",
        "output_help": "Directorio para guardar archivos convertidos; se usa el de trabajo si no se indica otro",
        "format_help": "Establecer el formato de salida:",
        "merge_help": "Por archivo de video, combinar con el audio de mismo nombre",
        "concat_help": "Concatenar archivos del mismo tipo (imagen/video/audio) uno tras otro",
        "framerate_help": "Establecer la tasa de fotogramas de salida (por defecto igual que la de entrada)",
        "quality_help": "Establecer la calidad de salida (alta, media, baja)",
        "delete_help": "Eliminar archivos originales tras la conversión",
        "web_help": "Ignora los demás argumentos y lanza el servidor web con interfaz",
        "across_help": "Ejecutar fusión o concatenación en todos los directorios de entrada en conjunto",
        "recursive_help": "Buscar archivos en subdirectorios de forma recursiva",
        "dropzone_help": "Zona de arrastre para convertir; se usa el directorio de entrada, se debe especificar otro de salida",
        "locale_help": f"Establecer el idioma para la CLI. El valor predeterminado es el idioma del sistema (soportados: {', '.join(LANGUAGE_CODES.keys())})",
        "lang_not_supported": f"Idioma no soportado (soportados: {', '.join(LANGUAGE_CODES.keys())})",
    },
    "Italian": {
        "title": "Convertitore di file",
        "select_file": "Seleziona file",
        "convert": "Converti",
        "download": "Scarica",
        "error": "Errore",
        "success": "Successo",
        "dropzone_diff": "La modalità dropzone richiede input e output distinti",
        "dropzone_active": "Modalità dropzone attiva. Premi CTRL+C per interrompere. Osservare:",
        "no_out_multi_in": "Percorso di output non specificato con percorsi di input multipli",
        "no_media_found": "Nessun file multimediale convertibile trovato in [path]",
        "skipping": "Saltando",
        "no_media_general": "Nessun file multimediale convertibile",
        "job_finished": "Lavoro completato",
        "output_list": "Il formato di output deve essere uno dei seguenti: [list]",
        "scheduling": "Programmo",
        "scanning": "Scansionando",
        "no_dir_exist": "La directory [dir] non esiste",
        "source_rate_incompatible": "La frequenza di campionamento sorgente non è compatibile con [format]. Viene utilizzata una frequenza compatibile...",
        "no_audio": "Nessun audio trovato in [path]",
        "audio_extract_fail": "Impossibile estrarre l'audio dal file audio [path]",
        "codec_fallback": "Codec incompatibile con [path]: provando il formato compatibile [format] invece...",
        "unsupported_stream": "Protocollo di streaming non supportato:",
        "get_hls": "Creazione di un flusso HLS per:",
        "get_hls_master": "Creazione della playlist principale per lo stream HLS:",
        "get_hls_fail": "Impossibile creare HLS:",
        "create_dash": "Creazione di un flusso DASH per:",
        "dash_fail": "Impossibile creare DASH:",
        "extract_subtitles": "Estrazione dei sottotitoli da:",
        "subtitles_success": "Sottotitoli estratti con successo in:",
        "extract_subtitles_alt": "Nessuna traccia di sottotitoli dedicata trovata. Provo a estrarre il testo incorporato...",
        "embed_subtitles_success": "Sottotitoli incorporati estratti con successo in:",
        "embed_subtitles_fail": "Impossibile estrarre i sottotitoli incorporati:",
        "extract_subtitles_fail": "Estrazione dei sottotitoli non riuscita:",
        "ffmpeg_not_found": "FFmpeg non trovato. Installa FFmpeg per estrarre i sottotitoli",
        "set_out_dir": "Impostazione della directory di output su:",
        "movie_format_unsupported": "Formato film non supportato:",
        "audio_only_video": "File vide o solo audio",
        "merging_pdfs": "Unendo [count] PDF in [path]",
        "unsupported_format": "Formato non supportato",
        "concat_success": "Concatenazione completata",
        "no_audio_movie_match": "Nessun file audio trovato per unire i file video",
        "converted": "Convertito",
        "removed": "Rimosso",
        "description": "Convertire file multimediali in formati diversi",
        "input_help": "Directory con file da convertire; se non specificata, viene usata quella di lavoro",
        "output_help": "Directory dove salvare i file convertiti; se non specificata, viene usata quella di lavoro",
        "format_help": "Imposta il formato di output:",
        "merge_help": "Per ogni video, unisci con l’audio avente lo stesso nome",
        "concat_help": "Concatena file dello stesso tipo (immagini/video/audio) in sequenza",
        "framerate_help": "Imposta il framerate di output (predefinito: uguale all’input)",
        "quality_help": "Imposta la qualità di output (alta, media, bassa)",
        "delete_help": "Elimina i file originali dopo la conversione",
        "web_help": "Ignora gli altri argomenti e avvia il server web con interfaccia",
        "across_help": "Esegui unione o concatenazione su tutte le directory di input, non singolarmente",
        "recursive_help": "Cerca file nelle sottodirectory in modo ricorsivo",
        "dropzone_help": "Area di rilascio per i file da convertire; si usa la directory di input e serve una di output distinta",
        "locale_help": f"Imposta la lingua per la CLI. Il valore predefinito è la lingua di sistema (supportate: {', '.join(LANGUAGE_CODES.keys())})",
        "lang_not_supported": f"Lingua non supportata (supportate: {', '.join(LANGUAGE_CODES.keys())})",
    },
    "German": {
        "title": "Datei-Konverter",
        "select_file": "Datei auswählen",
        "convert": "Konvertieren",
        "download": "Herunterladen",
        "error": "Fehler",
        "success": "Erfolg",
        "dropzone_diff": "Dropzone-Modus erfordert unterschiedliche Eingabe und Ausgabe",
        "dropzone_active": "Dropzone-Modus aktiv. Drücken Sie CTRL+C, um zu stoppen. Beobachte:",
        "no_out_multi_in": "Kein Ausgabepfad angegeben bei mehreren Eingabepfaden",
        "no_media_found": "Keine konvertierbaren Mediendateien in [path] gefunden",
        "skipping": "Überspringen",
        "no_media_general": "Keine konvertierbaren Mediendateien",
        "job_finished": "Job abgeschlossen",
        "output_list": "Das Ausgabeformat muss eines der folgenden sein: [list]",
        "scheduling": "Plane",
        "scanning": "Scanne",
        "no_dir_exist": "Verzeichnis [dir] existiert nicht",
        "source_rate_incompatible": "Quell-Abtastrate nicht kompatibel mit [format]. Versuche stattdessen kompatible Rate...",
        "no_audio": "Kein Audio in [path] gefunden",
        "audio_extract_fail": "Fehler beim Extrahieren von Audio aus Audio-Datei [path]",
        "codec_fallback": "Codec inkompatibel mit [path]: Versuche stattdessen kompatibles Format [format]...",
        "unsupported_stream": "Nicht unterstütztes Streaming-Protokoll:",
        "get_hls": "Erstelle HLS-Stream für:",
        "get_hls_master": "Erstelle Master-Playlist für HLS-Stream:",
        "get_hls_fail": "Fehler beim Erstellen von HLS:",
        "create_dash": "Erstelle DASH-Stream für:",
        "dash_fail": "Fehler beim Erstellen von DASH:",
        "extract_subtitles": "Untertitel extrahieren von:",
        "subtitles_success": "Untertitel erfolgreich extrahiert nach:",
        "extract_subtitles_alt": "Keine dedizierte Untertitelspur gefunden. Versuche, eingebetteten Text zu extrahieren...",
        "embed_subtitles_success": "Eingebettete Untertitel erfolgreich extrahiert nach:",
        "embed_subtitles_fail": "Fehler beim Extrahieren eingebetteter Untertitel:",
        "extract_subtitles_fail": "Extraktion der Untertitel fehlgeschlagen:",
        "ffmpeg_not_found": "FFmpeg nicht gefunden. Installieren Sie FFmpeg, um Untertitel zu extrahieren",
        "set_out_dir": "Setze Ausgabeverzeichnis auf:",
        "movie_format_unsupported": "Nicht unterstütztes Filmformat:",
        "audio_only_video": "Video-Datei enthält nur Audio",
        "merging_pdfs": "Füge [count] PDFs in [path] zusammen",
        "unsupported_format": "Nicht unterstütztes Format",
        "concat_success": "Konkatenation abgeschlossen",
        "no_audio_movie_match": "Keine Audio-Dateien gefunden, um sie mit Film-Dateien zu verbinden",
        "converted": "Konvertiert",
        "removed": "Entfernt",
        "description": "Konvertiere Mediendateien in verschiedenste Formate",
        "input_help": "Verzeichnis mit zu konvertierenden Dateien; Standard ist das Arbeitsverzeichnis",
        "output_help": "Verzeichnis zum Speichern der konvertierten Dateien; Standard ist das Arbeitsverzeichnis",
        "format_help": "Ausgabeformat festlegen:",
        "merge_help": "Pro Video mit gleichnamiger Audiodatei zusammenführen",
        "concat_help": "Dateien gleichen Typs (Bild/Video/Audio) aneinanderhängen",
        "framerate_help": "Ausgabe-Framerate festlegen (Standard: wie Eingabe)",
        "quality_help": "Ausgabequalität festlegen (hoch, mittel, niedrig)",
        "delete_help": "Quelldateien nach Konvertierung löschen",
        "web_help": "Ignoriert alle anderen Parameter und startet Webserver und Oberfläche",
        "across_help": "Zusammenführen/Verketten über alle Eingabeverzeichnisse hinweg",
        "recursive_help": "Dateien rekursiv in Unterordnern durchsuchen",
        "dropzone_help": "Ablagebereich für zu konvertierende Dateien; Eingabeverzeichnis wird verwendet, Ausgabeverzeichnis muss separat angegeben werden",
        "locale_help": f"Sprache für die CLI festlegen. Standard ist die Systemsprache (unterstützt: {', '.join(LANGUAGE_CODES.keys())})",
        "lang_not_supported": f"Sprache nicht unterstützt (unterstützt sind: {', '.join(LANGUAGE_CODES.keys())})",
    },
    "Portuguese": {
        "title": "Conversor de arquivos",
        "select_file": "Selecionar arquivo",
        "convert": "Converter",
        "download": "Baixar",
        "error": "Erro",
        "success": "Sucesso",
        "dropzone_diff": "O modo de transferência exige que origem e destino sejam diferentes",
        "dropzone_active": "Modo de transferência ativo. Pressione CTRL+C para parar. Observar:",
        "no_out_multi_in": "Nenhum caminho de saída fornecido ao usar vários caminhos de entrada",
        "no_media_found": "Nenhum arquivo de mídia convertível encontrado em [path]",
        "skipping": "Pulando",
        "no_media_general": "Nenhum arquivo de mídia convertível",
        "job_finished": "Trabalho concluído",
        "output_list": "O formato de saída deve ser um dos seguintes: [list]",
        "scheduling": "Agendando",
        "scanning": "Escaneando",
        "no_dir_exist": "O diretório [dir] não existe",
        "source_rate_incompatible": "Taxa de amostragem de origem incompatível com [format]. Tentando taxa compatível em vez disso...",
        "no_audio": "Nenhum áudio encontrado em [path]",
        "audio_extract_fail": "Falha ao extrair áudio do arquivo de áudio [path]",
        "codec_fallback": "Codec incompatível com [path]: tentando o formato compatível [format] em vez disso...",
        "unsupported_stream": "Protocolo de streaming não suportado:",
        "get_hls": "Criando stream HLS para:",
        "get_hls_master": "Criando playlist mestre para o stream HLS:",
        "get_hls_fail": "Falha ao criar HLS:",
        "create_dash": "Criando stream DASH para:",
        "dash_fail": "Falha ao criar DASH:",
        "extract_subtitles": "Extraindo legendas de:",
        "subtitles_success": "Legendas extraídas com sucesso para:",
        "extract_subtitles_alt": "Nenhuma faixa de legendas dedicada encontrada. Tentando extrair texto incorporado...",
        "embed_subtitles_success": "Legendas incorporadas extraídas com sucesso para:",
        "embed_subtitles_fail": "Falha ao extrair legendas incorporadas:",
        "extract_subtitles_fail": "Falha na extração de legendas:",
        "ffmpeg_not_found": "FFmpeg não encontrado. Instale o FFmpeg para extrair legendas",
        "set_out_dir": "Definindo o diretório de saída para:",
        "movie_format_unsupported": "Formato de filme não suportado:",
        "audio_only_video": "Arquivo de vídeo apenas de áudio",
        "merging_pdfs": "Mesclando [count] PDFs em [path]",
        "unsupported_format": "Formato não suportado",
        "concat_success": "Concatenação concluída",
        "no_audio_movie_match": "Nenhum arquivo de áudio encontrado para mesclar com arquivos de filme",
        "converted": "Convertido",
        "removed": "Removido",
        "description": "Converter arquivos de mídia para outros formatos",
        "input_help": "Diretório com arquivos a serem convertidos; usa o diretório de trabalho se não definido",
        "output_help": "Diretório para salvar os arquivos convertidos; usa o diretório de trabalho se não definido",
        "format_help": "Defina o formato de saída:",
        "merge_help": "Por arquivo de vídeo, juntar com áudio de mesmo nome",
        "concat_help": "Concatenar arquivos do mesmo tipo (imagem/vídeo/áudio) em sequência",
        "framerate_help": "Definir taxa de quadros de saída (padrão: igual à de entrada)",
        "quality_help": "Definir a qualidade de saída (alta, média, baixa)",
        "delete_help": "Excluir arquivos de entrada após conversão",
        "web_help": "Ignora outros argumentos e inicia o servidor web com interface",
        "across_help": "Executar mesclagem ou concatenação em todos os diretórios de entrada",
        "recursive_help": "Buscar arquivos nas subpastas de forma recursiva",
        "dropzone_help": "Área de soltar arquivos para conversão; diretório de entrada será usado, e é necessário definir outro para saída",
        "locale_help": f"Defina o idioma para a CLI. O padrão é o idioma do sistema (suportado: {', '.join(LANGUAGE_CODES.keys())})",
        "lang_not_supported": f"Idioma não suportado (suportado: {', '.join(LANGUAGE_CODES.keys())})",
    },
    "Russian": {
        "title": "Конвертер файлов",
        "select_file": "Выбрать файл",
        "convert": "Конвертировать",
        "download": "Скачать",
        "error": "Ошибка",
        "success": "Успех",
        "dropzone_diff": "Режим перетаскивания требует, чтобы ввод и вывод были явно различны",
        "dropzone_active": "Режим перетаскивания активен. Нажмите CTRL+C, чтобы остановить. Наблюдение:",
        "no_out_multi_in": "Не указан путь вывода при использовании нескольких путей ввода",
        "no_media_found": "В [path] не найдено конвертируемых медиафайлов",
        "skipping": "Пропуск",
        "no_media_general": "Нет конвертируемых медиафайлов",
        "job_finished": "Работа завершена",
        "output_list": "Формат вывода должен быть одним из следующих: [list]",
        "scheduling": "Планирование",
        "scanning": "Сканирование",
        "no_dir_exist": "Каталог [dir] не существует",
        "source_rate_incompatible": "Частота дискретизации источника и [format] несовместимы. Используется совместимая частота...",
        "no_audio": "В [path] не найдено аудио",
        "audio_extract_fail": "Не удалось извлечь аудио из файла с аудио [path]",
        "codec_fallback": "Кодек несовместим с [path]: пытаюсь использовать совместимый формат [format]...",
        "unsupported_stream": "Неподдерживаемый потоковый протокол:",
        "get_hls": "Создание HLS-потока для:",
        "get_hls_master": "Создание главного плейлиста для HLS-потока:",
        "get_hls_fail": "Не удалось создать HLS:",
        "create_dash": "Создание DASH-потока для:",
        "dash_fail": "Не удалось создать DASH:",
        "extract_subtitles": "Извлечение субтитров из:",
        "subtitles_success": "Субтитры успешно извлечены в:",
        "extract_subtitles_alt": "Не найдена выделенная дорожка субтитров. Пытаюсь извлечь встроенный текст...",
        "embed_subtitles_success": "Встроенные субтитры успешно извлечены в:",
        "embed_subtitles_fail": "Не удалось извлечь встроенные субтитры:",
        "extract_subtitles_fail": "Не удалось извлечь субтитры:",
        "ffmpeg_not_found": "FFmpeg не найден. Установите FFmpeg для извлечения субтитров",
        "set_out_dir": "Установка выходного каталога на:",
        "movie_format_unsupported": "Неподдерживаемый формат фильма:",
        "audio_only_video": "Только аудио видеофайл",
        "merging_pdfs": "Объединение [count] PDF в [path]",
        "unsupported_format": "Неподдерживаемый формат",
        "concat_success": "Конкатенация завершена",
        "no_audio_movie_match": "Не найдено аудиофайлов для объединения с видеофайлами",
        "converted": "Конвертировано",
        "removed": "Удалено",
        "description": "Конвертировать медиафайлы в разные форматы",
        "input_help": "Каталог с медиафайлами для конвертации; если не указан — используется рабочий каталог",
        "output_help": "Каталог для сохранения результата; если не указан — используется рабочий каталог",
        "format_help": "Установить формат вывода:",
        "merge_help": "Для каждого видео объединить с аудиофайлом с тем же именем",
        "concat_help": "Объединить файлы одного типа (изображение/видео/аудио) последовательно",
        "framerate_help": "Установить частоту кадров (по умолчанию — как у входного файла)",
        "quality_help": "Установить качество вывода (высокое, среднее, низкое)",
        "delete_help": "Удалить исходные файлы после конвертации",
        "web_help": "Игнорирует остальные аргументы, запускает веб-сервер и интерфейс",
        "across_help": "Объединение/склейка через все каталоги входа, а не по отдельности",
        "recursive_help": "Рекурсивный поиск файлов во вложенных папках",
        "dropzone_help": "Зона для перетаскивания файлов; используется входная папка, выходную нужно указать отдельно",
        "locale_help": f"Установить язык для CLI. По умолчанию используется системная локализация (поддерживается: {', '.join(LANGUAGE_CODES.keys())})",
        "lang_not_supported": f"Язык не поддерживается (поддерживаемые: {', '.join(LANGUAGE_CODES.keys())})",
    },
    "Korean": {
        "title": "파일 변환기",
        "select_file": "파일 선택",
        "convert": "변환",
        "download": "다운로드",
        "error": "오류",
        "success": "성공",
        "dropzone_diff": "드롭존 모드는 입력과 출력을 명확히 다르게 해야 합니다",
        "dropzone_active": "드롭존 모드 활성화. CTRL+C를 눌러 중지합니다. 관찰:",
        "no_out_multi_in": "여러 입력 경로를 사용할 때 출력 경로가 지정되지 않았습니다",
        "no_media_found": "[path] 에서 변환 가능한 미디어 파일을 찾을 수 없습니다",
        "skipping": "건너뜀",
        "no_media_general": "변환 가능한 미디어 파일이 없습니다",
        "job_finished": "작업 완료",
        "output_list": "출력 형식은 다음 중 하나여야 합니다: [list]",
        "scheduling": "일정",
        "scanning": "스캔 중",
        "no_dir_exist": "디렉토리 [dir]가 존재하지 않습니다",
        "source_rate_incompatible": "소스 샘플 속도가 [format]과 호환되지 않습니다. 대신 호환 가능한 속도를 사용합니다...",
        "no_audio": "[path] 에서 오디오를 찾을 수 없습니다",
        "audio_extract_fail": "오디오 전용 파일 [path]에서 오디오 추출에 실패했습니다", 
        "codec_fallback": "[path]와 호환되지 않는 코덱: 대신 호환 가능한 포맷 [format]을 시도 중...",
        "unsupported_stream": "지원되지 않는 스트리밍 프로토콜:",
        "get_hls": "HLS 스트림 생성 중:",
        "get_hls_master": "HLS 스트림의 마스터 재생 목록 생성 중:",
        "get_hls_fail": "HLS 생성 실패:",
        "create_dash": "DASH 스트림 생성 중:",
        "dash_fail": "DASH 생성 실패:",
        "extract_subtitles": "자막 추출 중:",
        "subtitles_success": "자막이 성공적으로 추출되었습니다:",
        "extract_subtitles_alt": "전용 자막 트랙을 찾을 수 없습니다. 내장된 텍스트를 추출하려고 시도 중...",
        "embed_subtitles_success": "내장된 자막이 성공적으로 추출되었습니다:",
        "embed_subtitles_fail": "내장된 자막 추출 실패:",
        "extract_subtitles_fail": "자막 추출 실패:",
        "ffmpeg_not_found": "FFmpeg를 찾을 수 없습니다. 자막을 추출하려면 FFmpeg를 설치하세요",
        "set_out_dir": "출력 디렉토리를 설정하는 중:",
        "movie_format_unsupported": "지원되지 않는 영화 형식:",
        "audio_only_video": "오디오 전용 비디오 파일",
        "merging_pdfs": "[count] PDF를 [path]에 병합하는 중",
        "unsupported_format": "지원되지 않는 형식",
        "concat_success": "연결 완료",
        "no_audio_movie_match": "비디오 파일과 병합할 오디오 파일을 찾을 수 없습니다",
        "converted": "변환됨",
        "removed": "제거됨",
        "description": "미디어 파일을 다른 형식으로 변환",
        "input_help": "변환할 미디어 파일이 있는 폴더, 지정하지 않으면 작업 디렉터리 사용",
        "output_help": "변환된 파일을 저장할 폴더, 지정하지 않으면 작업 디렉터리 사용",
        "format_help": "출력 형식 설정:",
        "merge_help": "동영상마다 동일한 이름의 오디오와 병합",
        "concat_help": "같은 유형의 파일(이미지/영상/오디오)을 순서대로 이어붙이기",
        "framerate_help": "출력 프레임레이트 설정 (기본값: 입력과 동일)",
        "quality_help": "출력 품질 설정 (높음, 중간, 낮음)",
        "delete_help": "변환 후 입력 파일 삭제",
        "web_help": "다른 인수를 무시하고 웹 서버와 프론트엔드 실행",
        "across_help": "각 입력 폴더별이 아닌 전체 입력에서 병합 또는 연결 실행",
        "recursive_help": "하위 폴더에서 파일을 재귀적으로 검색",
        "dropzone_help": "변환할 파일을 드롭하는 영역; 입력 폴더 사용, 출력은 별도로 지정 필요",
        "locale_help": f"CLI의 언어 설정. 기본값은 시스템 로케일입니다 (지원되는 언어: {', '.join(LANGUAGE_CODES.keys())})",
        "lang_not_supported": f"지원되지 않는 언어 (지원되는 언어: {', '.join(LANGUAGE_CODES.keys())})",
    },
    "English": {
        "title": "File Converter",
        "select_file": "Select File",
        "convert": "Convert",
        "download": "Download",
        "error": "Error",
        "success": "Success",
        "dropzone_diff": "Dropzone mode requires input and output to be distinctly different",
        "dropzone_active": "Dropzone mode active. Press CTRL+C to halt. Watching:",
        "no_out_multi_in": "No output path provided while using multiple input paths",
        "no_media_found": "No convertible media files found in [path]",
        "skipping": "Skipping",
        "no_media_general": "No convertible media files",
        "job_finished": "Job finished",
        "output_list": "Output format must be one of [list]",
        "scheduling": "Scheduling",
        "scanning": "Scanning",
        "no_dir_exist": "Directory [dir] does not exist",
        "source_rate_incompatible": "Source Sample Rate Incompatible With [format]. Trying Compatible Rate Instead...",
        "no_audio": "No audio found in [path]",
        "audio_extract_fail": "Failed to extract audio from audio-only file [path]",
        "codec_fallback": "Codec Incompatible with [path]: Trying Compatible Format [format] Instead...",
        "unsupported_stream": "Unsupported streaming protocol:",
        "get_hls": "Creating HLS stream for:",
        "get_hls_master": "Creating master playlist for HLS stream:",
        "get_hls_fail": "Failed to create HLS:",
        "create_dash": "Creating DASH stream for:",
        "dash_fail": "Failed to create DASH:",
        "extract_subtitles": "Extracting subtitles from:",
        "subtitles_success": "Subtitles successfully extracted to:",
        "extract_subtitles_alt": "No dedicated subtitle track found. Trying to extract embedded text...",
        "embed_subtitles_success": "Embedded subtitles successfully extracted to:",
        "embed_subtitles_fail": "No subtitles found for:",
        "extract_subtitles_fail": "Extraction of subtitles failed:",
        "ffmpeg_not_found": "FFmpeg not found. Install FFmpeg to extract subtitles",
        "set_out_dir": "Setting output directory to:",
        "movie_format_unsupported": "Unsupported movie format:",
        "audio_only_video": "Audio-only video file",
        "merging_pdfs": "Merging [count] PDFs into [path]",
        "unsupported_format": "Unsupported format",
        "concat_success": "Concatenation completed",
        "no_audio_movie_match": "No audio files found to merge with movie files",
        "converted": "Converted",
        "removed": "Removed",
        "description": "Convert media files to different formats",
        "input_help": "Directory containing media files to be converted, Working Directory if none provided",
        "output_help": "Directory to save converted files, Working Directory if none provided",
        "format_help": "Set the output format:",
        "merge_help": "Per movie file, merge to movie with equally named audio file",
        "concat_help": "Concatenate files of same type (img/movie/audio) back to back",
        "framerate_help": "Set the output framerate (default: same as input)",
        "quality_help": "Set the output quality (high, medium, low)",
        "delete_help": "Delete input files after conversion",
        "web_help": "Ignores all other arguments, starts web server + frontend",
        "across_help": "Execute merging or concatenation across all input directories, not per each individually",
        "recursive_help": "Recursively search for files in subdirectories for input",
        "dropzone_help": "Dropzone for files to be converted, input dir will be used, distinct output dir has to be specified",
        "locale_help": f"Set the language for the CLI. Default is system locale (supported: {', '.join(LANGUAGE_CODES.keys())})",
        "lang_not_supported": f"Language not supported (supported: {', '.join(LANGUAGE_CODES.keys())})",
    },
    "Polish": {
        "title": "Konwerter plików",
        "select_file": "Wybierz plik",
        "convert": "Konwertuj",
        "download": "Pobierz",
        "error": "Błąd",
        "success": "Sukces",
        "dropzone_diff": "Tryb Dropzone wymaga różnych katalogów wejściowego i wyjściowego",
        "dropzone_active": "Tryb Dropzone aktywny. Naciśnij CTRL+C, aby zatrzymać. Obserwowanie:",
        "no_out_multi_in": "Brak ścieżki wyjściowej przy wielu ścieżkach wejściowych",
        "no_media_found": "Nie znaleziono konwertowalnych plików multimedialnych w [path]",
        "skipping": "Pomijanie",
        "no_media_general": "Brak konwertowalnych plików multimedialnych",
        "job_finished": "Zadanie zakończone",
        "output_list": "Format wyjściowy musi być jednym z [list]",
        "scheduling": "Planowanie",
        "scanning": "Skanowanie",
        "no_dir_exist": "Katalog [dir] nie istnieje",
        "source_rate_incompatible": "Niekompatybilna częstotliwość próbkowania źródła z [format]. Próba użycia kompatybilnej częstotliwości...",
        "no_audio": "Nie znaleziono dźwięku w [path]",
        "audio_extract_fail": "Nie udało się wyodrębnić dźwięku z pliku zawierającego tylko dźwięk [path]",
        "codec_fallback": "Kodek niekompatybilny z [path]: Próba użycia kompatybilnego formatu [format]...",
        "unsupported_stream": "Nieobsługiwany protokół strumieniowania:",
        "get_hls": "Tworzenie strumienia HLS dla:",
        "get_hls_master": "Tworzenie głównej listy odtwarzania dla strumienia HLS:",
        "get_hls_fail": "Nie udało się utworzyć HLS:",
        "create_dash": "Tworzenie strumienia DASH dla:",
        "dash_fail": "Nie udało się utworzyć DASH:",
        "extract_subtitles": "Wyodrębnianie napisów z:",
        "subtitles_success": "Napisy pomyślnie wyodrębnione do:",
        "extract_subtitles_alt": "Nie znaleziono dedykowanej ścieżki napisów. Próba wyodrębnienia osadzonego tekstu...",
        "embed_subtitles_success": "Osadzone napisy pomyślnie wyodrębnione do:",
        "embed_subtitles_fail": "Nie znaleziono napisów dla:",
        "extract_subtitles_fail": "Nie udało się wyodrębnić napisów:",
        "ffmpeg_not_found": "Nie znaleziono FFmpeg. Zainstaluj FFmpeg, aby wyodrębnić napisy",
        "set_out_dir": "Ustawianie katalogu wyjściowego na:",
        "movie_format_unsupported": "Nieobsługiwany format filmu:",
        "audio_only_video": "Plik wideo zawierający tylko dźwięk",
        "merging_pdfs": "Scalanie [count] plików PDF do [path]",
        "unsupported_format": "Nieobsługiwany format",
        "concat_success": "Scalanie zakończone",
        "no_audio_movie_match": "Nie znaleziono plików audio do scalenia z plikami filmowymi",
        "converted": "Skonwertowano",
        "removed": "Usunięto",
        "description": "Konwertuj pliki multimedialne na różne formaty",
        "input_help": "Katalog zawierający pliki multimedialne do konwersji, katalog roboczy, jeśli nie podano",
        "output_help": "Katalog do zapisu skonwertowanych plików, katalog roboczy, jeśli nie podano",
        "format_help": "Ustaw format wyjściowy:",
        "merge_help": "Dla każdego pliku filmowego, scalić z plikiem audio o tej samej nazwie",
        "concat_help": "Scal pliki tego samego typu (obraz/film/dźwięk) jeden po drugim",
        "framerate_help": "Ustaw liczbę klatek na sekundę wyjściową (domyślnie: taka sama jak wejściowa)",
        "quality_help": "Ustaw jakość wyjściową (wysoka, średnia, niska)",
        "delete_help": "Usuń pliki wejściowe po konwersji",
        "web_help": "Ignoruje wszystkie inne argumenty, uruchamia serwer WWW + interfejs",
        "across_help": "Wykonaj scalanie lub łączenie we wszystkich katalogach wejściowych, a nie osobno dla każdego",
        "recursive_help": "Rekursywnie przeszukuj pliki w podkatalogach dla wejścia",
        "dropzone_help": "Strefa upuszczania dla plików do konwersji, używany będzie katalog wejściowy, należy określić odrębny katalog wyjściowy",
        "locale_help": f"Ustaw język dla CLI. Domyślnie jest to lokalizacja systemowa (obsługiwane: {', '.join(LANGUAGE_CODES.keys())})",
        "lang_not_supported": f"Język nie jest obsługiwany (obsługiwane: {', '.join(LANGUAGE_CODES.keys())})",
    },
    "Hindi": {
        "title": "फ़ाइल कन्वर्टर",
        "select_file": "फ़ाइल चुनें",
        "convert": "कन्वर्ट करें",
        "download": "डाउनलोड करें",
        "error": "त्रुटि",
        "success": "सफलता",
        "dropzone_diff": "ड्रॉपज़ोन मोड में इनपुट और आउटपुट अलग-अलग होने चाहिए",
        "dropzone_active": "ड्रॉपज़ोन मोड सक्रिय है। रोकने के लिए CTRL+C दबाएं। देख रहे हैं:",
        "no_out_multi_in": "एकाधिक इनपुट पथों के साथ आउटपुट पथ प्रदान नहीं किया गया",
        "no_media_found": "[path] में कोई कन्वर्ट करने योग्य मीडिया फ़ाइलें नहीं मिलीं",
        "skipping": "छोड़ रहे हैं",
        "no_media_general": "कोई कन्वर्ट करने योग्य मीडिया फ़ाइलें नहीं",
        "job_finished": "कार्य समाप्त हुआ",
        "output_list": "आउटपुट प्रारूप [list] में से एक होना चाहिए",
        "scheduling": "अनुसूची बनाना",
        "scanning": "स्कैनिंग",
        "no_dir_exist": "निर्देशिका [dir] मौजूद नहीं है",
        "source_rate_incompatible": "स्रोत सैंपल दर [format] के साथ असंगत है। इसके बजाय संगत दर का प्रयास कर रहे हैं...",
        "no_audio": "[path] में कोई ऑडियो नहीं मिला",
        "audio_extract_fail": "केवल ऑडियो फ़ाइल [path] से ऑडियो निकालने में विफल",
        "codec_fallback": "[path] के साथ कोडेक असंगत है: इसके बजाय संगत प्रारूप [format] का प्रयास कर रहे हैं...",
        "unsupported_stream": "असमर्थित स्ट्रीमिंग प्रोटोकॉल:",
        "get_hls": "इसके लिए HLS स्ट्रीम बना रहे हैं:",
        "get_hls_master": "HLS स्ट्रीम के लिए मास्टर प्लेलिस्ट बना रहे हैं:",
        "get_hls_fail": "HLS बनाने में विफल:",
        "create_dash": "इसके लिए DASH स्ट्रीम बना रहे हैं:",
        "dash_fail": "DASH बनाने में विफल:",
        "extract_subtitles": "से उपशीर्षक निकाल रहे हैं:",
        "subtitles_success": "उपशीर्षक सफलतापूर्वक निकाले गए:",
        "extract_subtitles_alt": "कोई समर्पित उपशीर्षक ट्रैक नहीं मिला। एम्बेडेड टेक्स्ट निकालने का प्रयास कर रहे हैं...",
        "embed_subtitles_success": "एम्बेडेड उपशीर्षक सफलतापूर्वक निकाले गए:",
        "embed_subtitles_fail": "के लिए कोई उपशीर्षक नहीं मिला:",
        "extract_subtitles_fail": "उपशीर्षक निकालने में विफल:",
        "ffmpeg_not_found": "FFmpeg नहीं मिला। उपशीर्षक निकालने के लिए FFmpeg स्थापित करें",
        "set_out_dir": "आउटपुट निर्देशिका सेट कर रहे हैं:",
        "movie_format_unsupported": "असमर्थित मूवी प्रारूप:",
        "audio_only_video": "केवल ऑडियो वीडियो फ़ाइल",
        "merging_pdfs": "[count] PDF को [path] में मर्ज कर रहे हैं",
        "unsupported_format": "असमर्थित प्रारूप",
        "concat_success": "संकलन पूरा हुआ",
        "no_audio_movie_match": "मूवी फ़ाइलों के साथ मर्ज करने के लिए कोई ऑडियो फ़ाइलें नहीं मिलीं",
        "converted": "कन्वर्ट किया गया",
        "removed": "हटाया गया",
        "description": "मीडिया फ़ाइलों को विभिन्न प्रारूपों में कन्वर्ट करें",
        "input_help": "कन्वर्ट करने के लिए मीडिया फ़ाइलों वाली निर्देशिका, यदि कोई नहीं दी गई तो कार्य निर्देशिका",
        "output_help": "कन्वर्ट की गई फ़ाइलों को सहेजने के लिए निर्देशिका, यदि कोई नहीं दी गई तो कार्य निर्देशिका",
        "format_help": "आउटपुट प्रारूप सेट करें:",
        "merge_help": "प्रत्येक मूवी फ़ाइल के लिए, समान नाम वाली ऑडियो फ़ाइल के साथ मर्ज करें",
        "concat_help": "एक ही प्रकार की फ़ाइलों (छवि/मूवी/ऑडियो) को एक के बाद एक जोड़ें",
        "framerate_help": "आउटपुट फ्रेमरेट सेट करें (डिफ़ॉल्ट: इनपुट के समान)",
        "quality_help": "आउटपुट गुणवत्ता सेट करें (उच्च, मध्यम, निम्न)",
        "delete_help": "कन्वर्ट करने के बाद इनपुट फ़ाइलें हटाएं",
        "web_help": "सभी अन्य तर्किबों की अनदेखी करता है, वेब सर्वर + फ्रंटएंड शुरू करता है",
        "across_help": "हर एक के बजाय सभी इनपुट निर्देशिकाओं में विलय या संयोजन करें",
        "recursive_help": "इनपुट के लिए उपनिर्देशिकाओं में फ़ाइलों को पुनरावृत्त रूप से खोजें",
        "dropzone_help": "कन्वर्ट करने के लिए फ़ाइलों के लिए ड्रॉपज़ोन, इनपुट निर्देशिका का उपयोग किया जाएगा, अलग आउटपुट निर्देशिका निर्दिष्ट करनी होगी",
        "locale_help": f"CLI के लिए भाषा सेट करें। डिफ़ॉल्ट सिस्टम स्थानीयता है (समर्थित: {', '.join(LANGUAGE_CODES.keys())})",
        "lang_not_supported": f"भाषा समर्थित नहीं है (समर्थित: {', '.join(LANGUAGE_CODES.keys())})",
    },
    "Ukrainian": {
        "title": "Конвертер файлів",
        "select_file": "Вибрати файл",
        "convert": "Конвертувати",
        "download": "Завантажити",
        "error": "Помилка",
        "success": "Успішно",
        "dropzone_diff": "Режим Dropzone вимагає різних вхідної та вихідної директорій",
        "dropzone_active": "Режим Dropzone активний. Натисніть CTRL+C для зупинки. Спостереження за:",
        "no_out_multi_in": "Не вказано шлях виводу при використанні кількох шляхів введення",
        "no_media_found": "Не знайдено медіафайлів для конвертації в [path]",
        "skipping": "Пропуск",
        "no_media_general": "Не знайдено медіафайлів для конвертації",
        "job_finished": "Завдання завершено",
        "output_list": "Формат виводу має бути одним з [list]",
        "scheduling": "Планування",
        "scanning": "Сканування",
        "no_dir_exist": "Каталог [dir] не існує",
        "source_rate_incompatible": "Частота дискретизації джерела несумісна з [format]. Спроба сумісної частоти...",
        "no_audio": "Аудіо не знайдено в [path]",
        "audio_extract_fail": "Не вдалося витягти аудіо з файлу тільки з аудіо [path]",
        "codec_fallback": "Кодек несумісний з [path]: спроба сумісного формату [format]...",
        "unsupported_stream": "Непідтримуваний протокол трансляції:",
        "get_hls": "Створення HLS потоку для:",
        "get_hls_master": "Створення головного плейлиста для HLS потоку:",
        "get_hls_fail": "Не вдалося створити HLS:",
        "create_dash": "Створення DASH потоку для:",
        "dash_fail": "Не вдалося створити DASH:",
        "extract_subtitles": "Витяг субтитрів з:",
        "subtitles_success": "Субтитри успішно збережено до:",
        "extract_subtitles_alt": "Присвяченої доріжки субтитрів не знайдено. Спроба витягти вбудований текст...",
        "embed_subtitles_success": "Вбудовані субтитри успішно збережено до:",
        "embed_subtitles_fail": "Субтитри не знайдені для:",
        "extract_subtitles_fail": "Не вдалося витягти субтитри:",
        "ffmpeg_not_found": "FFmpeg не знайдено. Встановіть FFmpeg для витягу субтитрів",
        "set_out_dir": "Встановлення вихідної директорії на:",
        "movie_format_unsupported": "Непідтримуваний формат відео:",
        "audio_only_video": "Відеофайл тільки з аудіо",
        "merging_pdfs": "Об'єднання [count] PDF у [path]",
        "unsupported_format": "Непідтримуваний формат",
        "concat_success": "Об'єднання завершено",
        "no_audio_movie_match": "Не знайдено аудіофайлів для об'єднання з відеофайлами",
        "converted": "Конвертовано",
        "removed": "Видалено",
        "description": "Конвертація медіафайлів у різні формати",
        "input_help": "Каталог з медіафайлами для конвертації, якщо не вказано — поточний каталог",
        "output_help": "Каталог для збереження конвертованих файлів, якщо не вказано — поточний каталог",
        "format_help": "Встановити формат виводу:",
        "merge_help": "Для кожного відеофайлу об'єднати з однойменним аудіофайлом",
        "concat_help": "Об'єднати файли одного типу (зображення/відео/аудіо) послідовно",
        "framerate_help": "Встановити частоту кадрів для виводу (за замовчуванням — як у вхідному файлі)",
        "quality_help": "Встановити якість виводу (висока, середня, низька)",
        "delete_help": "Видалити вхідні файли після конвертації",
        "web_help": "Ігнорує всі інші аргументи, запускає веб-сервер і інтерфейс",
        "across_help": "Виконувати об'єднання або злиття по всіх вхідних директоріях, а не по одній",
        "recursive_help": "Рекурсивно шукати файли в підкаталогах",
        "dropzone_help": "Область для перетягування файлів для конвертації. Використовується вхідна директорія, потрібно вказати іншу вихідну",
        "locale_help": f"Встановити мову для CLI. За замовчуванням - системна локаль (підтримуються: {', '.join(LANGUAGE_CODES.keys())})",
        "lang_not_supported": f"Мова не підтримується (підтримуються: {', '.join(LANGUAGE_CODES.keys())})",
    },
    "Arabic": {
        "title": "محول الملفات",
        "select_file": "اختر ملف",
        "convert": "تحويل",
        "download": "تنزيل",
        "error": "خطأ",
        "success": "نجاح",
        "dropzone_diff": "يتطلب وضع Dropzone اختلافاً واضحاً بين المصدر والوجهة",
        "dropzone_active": "وضع Dropzone نشط. اضغط CTRL+C للإيقاف. جارى المراقبة:",
        "no_out_multi_in": "لم يتم توفير مسار إخراج أثناء استخدام عدة مسارات إدخال",
        "no_media_found": "لم يتم العثور على ملفات وسائط قابلة للتحويل في [path]",
        "skipping": "تخطي",
        "no_media_general": "لا توجد ملفات وسائط قابلة للتحويل",
        "job_finished": "تم انتهاء المهمة",
        "output_list": "يجب أن يكون تنسيق الإخراج واحداً من [list]",
        "scheduling": "جارٍ الجدولة",
        "scanning": "جارٍ الفحص",
        "no_dir_exist": "المجلد [dir] غير موجود",
        "source_rate_incompatible": "معدل العينة للمصدر غير متوافق مع [format]. المحاولة بمعدل متوافق بدلاً من ذلك...",
        "no_audio": "لم يتم العثور على صوت في [path]",
        "audio_extract_fail": "فشل استخراج الصوت من الملف الصوتي [path]",
        "codec_fallback": "البرنامج الترميزي غير متوافق مع [path]: المحاولة بالتنسيق المتوافق [format] بدلاً من ذلك...",
        "unsupported_stream": "بروتوكول البث غير مدعوم:",
        "get_hls": "إنشاء تيار HLS لـِ:",
        "get_hls_master": "إنشاء قائمة تشغيل رئيسية لتيار HLS لـِ:",
        "get_hls_fail": "فشل إنشاء HLS:",
        "create_dash": "إنشاء تيار DASH لـِ:",
        "dash_fail": "فشل إنشاء DASH:",
        "extract_subtitles": "جارٍ استخراج الترجمة من:",
        "subtitles_success": "تم استخراج الترجمة بنجاح إلى:",
        "extract_subtitles_alt": "لم يتم العثور على مسار ترجمة مخصص. المحاولة لاستخراج النص المضمن...",
        "embed_subtitles_success": "تم استخراج الترجمة المضمنة بنجاح إلى:",
        "embed_subtitles_fail": "لم يتم العثور على ترجمة لـِ:",
        "extract_subtitles_fail": "فشل استخراج الترجمة:",
        "ffmpeg_not_found": "لم يتم العثور على FFmpeg. قم بتثبيت FFmpeg لاستخراج الترجمات",
        "set_out_dir": "تعيين مجلد الإخراج إلى:",
        "movie_format_unsupported": "تنسيق الفيلم غير مدعوم:",
        "audio_only_video": "ملف فيديو صوتي فقط",
        "merging_pdfs": "جارٍ دمج [count] ملفات PDF في [path]",
        "unsupported_format": "تنسيق غير مدعوم",
        "concat_success": "اكتمل الدمج",
        "no_audio_movie_match": "لم يتم العثور على ملفات صوت لدمجها مع ملفات الفيديو",
        "converted": "تم التحويل",
        "removed": "تم الحذف",
        "description": "تحويل ملفات الوسائط إلى صيغ مختلفة",
        "input_help": "المجلد الذي يحتوي على ملفات الوسائط للتحويل، المجلد الحالي إذا لم يتم تحديده",
        "output_help": "المجلد لحفظ الملفات المحولة، المجلد الحالي إذا لم يتم تحديده",
        "format_help": "تعيين تنسيق الإخراج:",
        "merge_help": "لدمج كل فيديو مع ملف صوت يحمل الاسم نفسه",
        "concat_help": "لربط الملفات من نفس النوع (صورة/فيديو/صوت) بالتسلسل",
        "framerate_help": "تعيين معدل الإطارات للإخراج (الافتراضي: نفس المصدر)",
        "quality_help": "تعيين جودة الإخراج (عالية، متوسطة، منخفضة)",
        "delete_help": "حذف ملفات المصدر بعد التحويل",
        "web_help": "تجاهل جميع المعاملات الأخرى وبدء خادم الويب والواجهة",
        "across_help": "التنفيذ عبر جميع مجلدات الإدخال معاً بدل كلٍ على حدة",
        "recursive_help": "البحث في المجلدات الفرعية بشكل متكرر للملفات المدخلة",
        "dropzone_help": "منطقة إسقاط للملفات المراد تحويلها؛ يُستخدم مجلد الإدخال، ويجب تحديد مجلد إخراج منفصل",
        "locale_help": f"تعيين اللغة لواجهة الأوامر. الافتراضي هو لغة النظام (مدعومة: {', '.join(LANGUAGE_CODES.keys())})",
        "lang_not_supported": f"اللغة غير مدعومة (المدعومة: {', '.join(LANGUAGE_CODES.keys())})",
    },
    "Indonesian": {
        "title": "Pengonversi Berkas",
        "select_file": "Pilih Berkas",
        "convert": "Konversi",
        "download": "Unduh",
        "error": "Kesalahan",
        "success": "Sukses",
        "dropzone_diff": "Mode Dropzone mengharuskan sumber dan tujuan berbeda secara jelas",
        "dropzone_active": "Mode Dropzone aktif. Tekan CTRL+C untuk berhenti. Mengawasi:",
        "no_out_multi_in": "Tidak ada jalur keluaran yang diberikan saat menggunakan beberapa jalur masukan",
        "no_media_found": "Tidak ada berkas media yang dapat dikonversi di [path]",
        "skipping": "Melewati",
        "no_media_general": "Tidak ada berkas media yang dapat dikonversi",
        "job_finished": "Pekerjaan selesai",
        "output_list": "Format keluaran harus salah satu dari [list]",
        "scheduling": "Menjadwalkan",
        "scanning": "Memindai",
        "no_dir_exist": "Direktori [dir] tidak ada",
        "source_rate_incompatible": "Laju sampel sumber tidak kompatibel dengan [format]. Mencoba laju yang kompatibel...",
        "no_audio": "Tidak ada audio ditemukan di [path]",
        "audio_extract_fail": "Gagal mengekstrak audio dari berkas audio [path]",
        "codec_fallback": "Kodek tidak kompatibel dengan [path]: Mencoba format kompatibel [format]...",
        "unsupported_stream": "Protokol streaming tidak didukung:",
        "get_hls": "Membuat aliran HLS untuk:",
        "get_hls_master": "Membuat daftar putar master untuk aliran HLS:",
        "get_hls_fail": "Gagal membuat HLS:",
        "create_dash": "Membuat aliran DASH untuk:",
        "dash_fail": "Gagal membuat DASH:",
        "extract_subtitles": "Mengekstrak teks terjemahan dari:",
        "subtitles_success": "Teks terjemahan berhasil diekstrak ke:",
        "extract_subtitles_alt": "Tidak ditemukan trek terjemahan khusus. Mencoba mengekstrak teks yang disematkan...",
        "embed_subtitles_success": "Teks terjemahan yang disematkan berhasil diekstrak ke:",
        "embed_subtitles_fail": "Tidak ada terjemahan ditemukan untuk:",
        "extract_subtitles_fail": "Ekstraksi teks terjemahan gagal:",
        "ffmpeg_not_found": "FFmpeg tidak ditemukan. Instal FFmpeg untuk mengekstrak terjemahan",
        "set_out_dir": "Menetapkan direktori keluaran ke:",
        "movie_format_unsupported": "Format film tidak didukung:",
        "audio_only_video": "Berkas video hanya berisi audio",
        "merging_pdfs": "Menggabungkan [count] PDF ke dalam [path]",
        "unsupported_format": "Format tidak didukung",
        "concat_success": "Penggabungan selesai",
        "no_audio_movie_match": "Tidak ada berkas audio untuk digabung dengan berkas video",
        "converted": "Dikonversi",
        "removed": "Dihapus",
        "description": "Mengonversi berkas media ke berbagai format",
        "input_help": "Direktori yang berisi berkas media untuk dikonversi, Direktori kerja jika tidak ditentukan",
        "output_help": "Direktori untuk menyimpan berkas yang dikonversi, Direktori kerja jika tidak ditentukan",
        "format_help": "Atur format keluaran:",
        "merge_help": "Gabungkan setiap video dengan berkas audio yang memiliki nama sama",
        "concat_help": "Satukan berkas dengan jenis sama (gambar/video/audio) secara berurutan",
        "framerate_help": "Atur kecepatan bingkai keluaran (default: sama dengan input)",
        "quality_help": "Atur kualitas keluaran (tinggi, sedang, rendah)",
        "delete_help": "Hapus berkas sumber setelah konversi",
        "web_help": "Abaikan semua argumen lain, mulai server web + antarmuka",
        "across_help": "Jalankan penggabungan atau penyatuan di semua direktori masukan sekaligus",
        "recursive_help": "Cari berkas secara rekursif di subdirektori masukan",
        "dropzone_help": "Zona Dropzone untuk berkas yang akan dikonversi; direktori masukan digunakan, direktori keluaran harus ditentukan terpisah",
        "locale_help": f"Atur bahasa untuk CLI. Default adalah locale sistem (didukung: {', '.join(LANGUAGE_CODES.keys())})",
        "lang_not_supported": f"Bahasa tidak didukung (didukung: {', '.join(LANGUAGE_CODES.keys())})",
    },
}


def get_system_language():
    lang_code = locale.getlocale()[0] or "en_US"
    # Try mapping to any of the supported languages
    for code, lang in LANGUAGE_CODES.items():
        if lang_code in code:
            return lang
    # Fallback to English
    return "English"


def get_translation(key, language=None):
    if language is None:
        language = get_system_language()
    # Fallback to English on missing translation
    return TRANSLATIONS.get(language, TRANSLATIONS["English"]).get(key, key)


def get_all_translations(language=None):
    if language is None:
        language = get_system_language()
    # Fallback to English if lang not supported
    return TRANSLATIONS.get(language, TRANSLATIONS["English"])
